[package]

name = "cql"
version = "0.0.2"
authors = ["Ignacio MartÃ­n <natx.mc@gmail.com>"]

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid.git"

[dependencies.num]

git = "https://github.com/rust-lang/num"

[dependencies]
byteorder = "*"

[dependencies]
enum_primitive = "*"
